# Generated by Django 4.2.4 on 2023-09-27 11:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('difficulty', models.CharField(choices=[('hard', '難'), ('medium', '中'), ('easy', '易')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StdCourseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_start', models.DateField()),
                ('status', models.CharField(choices=[('great', '非常好'), ('soso', '普通'), ('bad', '不好')], max_length=20)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_server.coursesinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('man', '男'), ('woman', '女')], max_length=20)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(40)])),
                ('school', models.CharField(max_length=25)),
                ('hobby', models.CharField(blank=True, max_length=20)),
                ('courses', models.ManyToManyField(through='api_server.StdCourseStatus', to='api_server.coursesinfo')),
            ],
        ),
        migrations.AddField(
            model_name='stdcoursestatus',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_server.student'),
        ),
    ]
