# Generated by Django 4.2.4 on 2023-09-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stdcoursestatus',
            unique_together={('courses', 'students')},
        ),
    ]
